name: Build and publish electron app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_for_linux:
    name: Build for linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: Build and release Linux binaries
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T linux --icon=/src-electron/icons/icon.png
  build_for_windows_x64:
    name: Build for windows
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: Build and release Windows binaries 
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T win32 --icon=/src-electron/icons/icon.ico
  build_for_macos_13:
    name: Build for MacOS-13
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
      - name: dmg-license add
        run: |
          sudo npm install -g dmg-license
      - name: Build and release MacOS-13 binaries
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T darwin --icon=/src-electron/icons/icon.icns
